# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c280d0129b5acc732dd2761d795fac20944e61a50d9060190a867bbc97a76ff581fb3a03bdeae18230e9dcdf9f73b355a467615412595c43929c7ac12d7a3704

test:
  secret_key_base: dcbb4a6703e8f94f08b356f2bddbf1299246e83d18942166959be655eb0dec5d68a0d1f185bc11ad0b799e87658774dce87a45b494964bd923d48db0aafaee4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
